# Path of the folder to watch
watch_folder = "/tmp/paperdump_in"

# Where processed documents should be moved
destination_folder = "/tmp/paperdump_out"

# Language passed to Tesseract
language = "eng"

# Delay before processing a file. Documents are uploaded by chunks,
# we have to wait until the transfer is complete.
# By default, files will be processed 2 minutes after the last chunk is received.
# We recommend not going below 30 sec
process_delay = "30s"
